version: '3.5'

services:
  db_server:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: testing_with_docker_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${PWD}/scripts/:/scripts
